server:
  port: 8080

spring:
  application:
    name: document-workflow-platform

  profiles:
    active: dev

  mongodb:
    uri: mongodb://admin:admin123@localhost:27017/document_workflow_db?authSource=admin
    auto-index-creation: true

logging:
  level:
    root: INFO
    com.manasbhat.documentworkflowplatform: DEBUG

app:
  jwt:
    secret: ThisIsATemporaryDevOnlySecretKeyChangeInProdMinimum256Bits
    expiration-ms: 86400000